### ISSUE TITLE
Info on upcoming MovieNight

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#11]
The MoviePolls site should crossreference to the corresponding MovieNight instance to direct users there when a movie is watched.

Requirements:
Show some sort of notification if a movienight is planned (and/or running)
    - maybe with some sort of closeable banner?
Save link to the MovieNight instance in the database

Questions to be asked:
Maybe use a countdown for the upcoming movienight?
Should we request the movienight url to check if the movie is running already?

**Comment by zorchenhimer** [comment]
A notification banner on-site that's something along the lines of "A movie is currently playing" with a link would be really nice.  I hadn't thought of that.

This would probably require some API on the MovieNight server in order to work nicely, but I'm OK with adding that functionality.

As for the countdown, this would have to rely on the End date being set on a cycle.  This isn't required to be set, but it would probably be nice to have a countdown if it is set for the current cycle.

**Comment by CptPie** [comment]
- [ ] countdown to next movienight
- [ ] link to running movienight?
