### ISSUE TITLE
Add different grid layout options.

### ISSUE THREAD

**Issue by LukeIsCodingNet** [zorchenhimer/MoviePolls#80]
Add a feature that would allow the user to change how the layout of the current cycle page is. How it is now, one movie per page, 2 per page, ect.

**Comment by CptPie** [comment]
The current layout of the cycle page adjusts based on the width of the browser window and is not hardcoded.
Aside from that i am not even possible how that would be realizable without "hardcoding" css in the template instead of the existing stylesheet.

As for my two cents i would be heavily opposed to hardcoding css in the template, especially since a redesign of the pages is in the works.

**Comment by CptPie** [comment]
Just a heads up for @LukeIsCodingNet, i asked about zorchs opinion on yesterdays (16.09.2020) stream and he has the same thoughts as myself.

**Comment by zorchenhimer** [comment]
Ah, yea, I forgot to comment on this.

Adding in layout options for the main page would only complicate things right now.  Also, having only two or three movies per page is not nearly enough.  The past few cycles have had ties for 1st, 2nd, 3rd, and/or 4th position.  Spreading these ties across multiple pages would only serve to confuse people.
